"""agrega permiso_ubicacion (HU 21, usado por filtro de HU 07)

Revision ID: 286308e821ed
Revises: bafc29b2ad8a
Create Date: 2026-07-21 15:30:56.342026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286308e821ed'
down_revision: Union[str, Sequence[str], None] = 'bafc29b2ad8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prms_ubccn',
    sa.Column('id_prms_ubc', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usr', sa.Integer(), nullable=False),
    sa.Column('id_ubccn', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ubccn'], ['ubccn.id_ubccn'], ),
    sa.ForeignKeyConstraint(['id_usr'], ['usr.id_usr'], ),
    sa.PrimaryKeyConstraint('id_prms_ubc'),
    sa.UniqueConstraint('id_usr', 'id_ubccn', name='uq_prmsubccn_usr_ubccn')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prms_ubccn')
    # ### end Alembic commands ###
