"""estructura inicial: cliente, sede, rol, usuario, ubicacion, conexion_ftp

Revision ID: bafc29b2ad8a
Revises:
Create Date: 2026-07-20 19:47:42.492111

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bafc29b2ad8a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clnt",
        sa.Column("id_clnt", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rzn_scl", sa.String(length=200), nullable=False),
        sa.Column("rc", sa.String(length=11), nullable=False),
        sa.Column("crr_cntct", sa.String(length=150), nullable=False),
        sa.Column("tlfn_cntct", sa.String(length=20), nullable=True),
        sa.Column("estd", sa.String(length=20), server_default="Activo", nullable=False),
        sa.Column(
            "fch_rgstr",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id_clnt"),
        sa.UniqueConstraint("rc"),
    )
    op.create_table(
        "rl",
        sa.Column("id_rl", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nmbr", sa.String(length=50), nullable=False),
        sa.Column("dscrpcn", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id_rl"),
        sa.UniqueConstraint("nmbr"),
    )
    op.create_table(
        "sd",
        sa.Column("id_sd", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_clnt", sa.Integer(), nullable=False),
        sa.Column("nmbr", sa.String(length=150), nullable=False),
        sa.Column("dscrpcn", sa.String(length=300), nullable=True),
        sa.Column("estd", sa.String(length=20), server_default="Activa", nullable=False),
        sa.Column(
            "fch_crcn", sa.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["id_clnt"],
            ["clnt.id_clnt"],
        ),
        sa.PrimaryKeyConstraint("id_sd"),
    )
    op.create_table(
        "usr",
        sa.Column("id_usr", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_rl", sa.Integer(), nullable=False),
        sa.Column("scp", sa.String(length=20), server_default="por_sede", nullable=False),
        sa.Column("nmbr_cmplt", sa.String(length=150), nullable=False),
        sa.Column("crr", sa.String(length=150), nullable=False),
        sa.Column("cntrsn_hsh", sa.String(length=255), nullable=False),
        sa.Column("zn_hrr", sa.String(length=50), server_default="America/Lima", nullable=False),
        sa.Column("estd", sa.String(length=20), server_default="Activo", nullable=False),
        sa.Column("intnts_fllds", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "fch_crcn", sa.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False
        ),
        sa.CheckConstraint("scp IN ('global','por_sede')", name="usr_scp_check"),
        sa.ForeignKeyConstraint(
            ["id_rl"],
            ["rl.id_rl"],
        ),
        sa.PrimaryKeyConstraint("id_usr"),
        sa.UniqueConstraint("crr"),
    )
    op.create_table(
        "cnxn_ftp",
        sa.Column("id_cnxn", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_sd", sa.Integer(), nullable=False),
        sa.Column("nmbr", sa.String(length=150), nullable=False),
        sa.Column("prtcl", sa.String(length=10), server_default="FTP", nullable=False),
        sa.Column("hst", sa.String(length=255), nullable=False),
        sa.Column("prt", sa.Integer(), server_default="21", nullable=False),
        sa.Column("usr_ftp", sa.String(length=100), nullable=True),
        sa.Column("crdncl_cfrd", sa.String(length=500), nullable=False),
        sa.Column("rt_rmt", sa.String(length=300), nullable=True),
        sa.Column("frcnc_mnts", sa.Integer(), server_default="15", nullable=False),
        sa.Column("estd", sa.String(length=20), server_default="Activa", nullable=False),
        sa.CheckConstraint(
            "prtcl <> 'FTP' OR (usr_ftp IS NOT NULL AND rt_rmt IS NOT NULL)",
            name="cnxnftp_ftp_obligatorio_check",
        ),
        sa.CheckConstraint("prtcl IN ('FTP','TCP')", name="cnxnftp_prtcl_check"),
        sa.ForeignKeyConstraint(
            ["id_sd"],
            ["sd.id_sd"],
        ),
        sa.PrimaryKeyConstraint("id_cnxn"),
    )
    op.create_table(
        "ubccn",
        sa.Column("id_ubccn", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_sd", sa.Integer(), nullable=False),
        sa.Column("nmbr", sa.String(length=150), nullable=False),
        sa.Column("dscrpcn", sa.String(length=300), nullable=True),
        sa.Column("lttd", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("lngtd", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("plgn_gjsn", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("estd", sa.String(length=20), server_default="Activa", nullable=False),
        sa.Column(
            "fch_crcn", sa.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False
        ),
        sa.CheckConstraint("lngtd BETWEEN -180 AND 180", name="ubccn_lngtd_check"),
        sa.CheckConstraint("lttd BETWEEN -90 AND 90", name="ubccn_lttd_check"),
        sa.ForeignKeyConstraint(
            ["id_sd"],
            ["sd.id_sd"],
        ),
        sa.PrimaryKeyConstraint("id_ubccn"),
        sa.UniqueConstraint("id_sd", "nmbr", name="uq_ubccn_sd_nombre"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ubccn")
    op.drop_table("cnxn_ftp")
    op.drop_table("usr")
    op.drop_table("sd")
    op.drop_table("rl")
    op.drop_table("clnt")
    # ### end Alembic commands ###
