"""agrega archivo_ingesta HT-05 HU09

Revision ID: e6abd89f4da3
Revises: 286308e821ed
Create Date: 2026-07-22 12:23:21.485965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6abd89f4da3'
down_revision: Union[str, Sequence[str], None] = '286308e821ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archv_ingst',
    sa.Column('id_archv', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cnxn', sa.Integer(), nullable=False),
    sa.Column('nmbr_archv', sa.String(length=300), nullable=False),
    sa.Column('estd', sa.String(length=20), server_default='Pendiente', nullable=False),
    sa.Column('fch_dtccn', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('fch_prcsd', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('mnsj_errr', sa.String(length=500), nullable=True),
    sa.Column('rgstrs_prcsds', sa.Integer(), nullable=True),
    sa.CheckConstraint("estd IN ('Pendiente','Procesando','Exitoso','Fallido')", name='archvingst_estd_check'),
    sa.ForeignKeyConstraint(['id_cnxn'], ['cnxn_ftp.id_cnxn'], ),
    sa.PrimaryKeyConstraint('id_archv')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('archv_ingst')
    # ### end Alembic commands ###
