"""esquema completo: suscripciones, mapeo, dispositivo, telemetria, paneles, alarmas, auditoria

Revision ID: eadc512979fc
Revises: e6abd89f4da3
Create Date: 2026-07-22 14:54:41.049800

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eadc512979fc"
down_revision: Union[str, Sequence[str], None] = "e6abd89f4da3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pln_sscrpcn",
        sa.Column("id_pln", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nmbr", sa.String(length=100), nullable=False),
        sa.Column("dscrpcn", sa.String(length=300), nullable=True),
        sa.Column("prc_mnsl", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("estd", sa.String(length=20), server_default="Activo", nullable=False),
        sa.PrimaryKeyConstraint("id_pln"),
        sa.UniqueConstraint("nmbr"),
    )
    op.create_table(
        "prmtr",
        sa.Column("id_prmtr", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nmbr", sa.String(length=100), nullable=False),
        sa.Column("undd", sa.String(length=30), nullable=False),
        sa.Column("dscrpcn", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id_prmtr"),
        sa.UniqueConstraint("nmbr"),
    )
    op.create_table(
        "lmt_pln",
        sa.Column("id_lmt", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_pln", sa.Integer(), nullable=False),
        sa.Column("mx_sds", sa.Integer(), server_default="1", nullable=False),
        sa.Column("mx_ubccns", sa.Integer(), nullable=False),
        sa.Column("mx_dspstvs", sa.Integer(), nullable=False),
        sa.Column("mx_usrs", sa.Integer(), nullable=False),
        sa.CheckConstraint("mx_dspstvs >= 0", name="lmtpln_mxdspstvs_check"),
        sa.CheckConstraint("mx_sds >= 0", name="lmtpln_mxsds_check"),
        sa.CheckConstraint("mx_ubccns >= 0", name="lmtpln_mxubccns_check"),
        sa.CheckConstraint("mx_usrs >= 0", name="lmtpln_mxusrs_check"),
        sa.ForeignKeyConstraint(
            ["id_pln"],
            ["pln_sscrpcn.id_pln"],
        ),
        sa.PrimaryKeyConstraint("id_lmt"),
        sa.UniqueConstraint("id_pln"),
    )
    op.create_table(
        "sscrpcn",
        sa.Column("id_sscrpcn", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_clnt", sa.Integer(), nullable=False),
        sa.Column("id_pln", sa.Integer(), nullable=False),
        sa.Column("fch_inc", sa.Date(), nullable=False),
        sa.Column("fch_vncmnt", sa.Date(), nullable=False),
        sa.Column("estd", sa.String(length=20), server_default="Activa", nullable=False),
        sa.ForeignKeyConstraint(
            ["id_clnt"],
            ["clnt.id_clnt"],
        ),
        sa.ForeignKeyConstraint(
            ["id_pln"],
            ["pln_sscrpcn.id_pln"],
        ),
        sa.PrimaryKeyConstraint("id_sscrpcn"),
    )
    op.create_index("idx_sscrpcn_vncmnt", "sscrpcn", ["fch_vncmnt", "estd"], unique=False)
    op.create_table(
        "cbr",
        sa.Column("id_cbr", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_sscrpcn", sa.Integer(), nullable=False),
        sa.Column("mnt", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("fch_cbr", sa.Date(), nullable=False),
        sa.Column("mtd_pg", sa.String(length=30), nullable=False),
        sa.Column(
            "fch_rgstr",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint("fch_cbr <= CURRENT_DATE", name="cbr_fchcbr_check"),
        sa.ForeignKeyConstraint(
            ["id_sscrpcn"],
            ["sscrpcn.id_sscrpcn"],
        ),
        sa.PrimaryKeyConstraint("id_cbr"),
    )
    op.create_table(
        "exprtcn",
        sa.Column("id_exprtcn", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("id_usr", sa.Integer(), nullable=False),
        sa.Column("frmt", sa.String(length=10), nullable=False),
        sa.Column("fltrs_aplcds", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("estd", sa.String(length=20), server_default="En proceso", nullable=False),
        sa.Column("url_dscrg", sa.String(length=500), nullable=True),
        sa.Column(
            "fch_slctd",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("fch_exprcn", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_usr"],
            ["usr.id_usr"],
        ),
        sa.PrimaryKeyConstraint("id_exprtcn"),
    )
    op.create_table(
        "lg_adtr",
        sa.Column("id_evnt", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("id_usr", sa.Integer(), nullable=False),
        sa.Column("id_sd", sa.Integer(), nullable=True),
        sa.Column("accn", sa.String(length=50), nullable=False),
        sa.Column("entdd", sa.String(length=50), nullable=False),
        sa.Column("vlrs_antrrs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("vlrs_nvs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "fch_evnt", sa.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["id_sd"],
            ["sd.id_sd"],
        ),
        sa.ForeignKeyConstraint(
            ["id_usr"],
            ["usr.id_usr"],
        ),
        sa.PrimaryKeyConstraint("id_evnt"),
    )
    op.create_index("idx_lgadtr_sd_fch", "lg_adtr", ["id_sd", "fch_evnt"], unique=False)
    op.create_index("idx_lgadtr_usr_fch", "lg_adtr", ["id_usr", "fch_evnt"], unique=False)
    op.create_table(
        "mp_frmt",
        sa.Column("id_mp", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_sd", sa.Integer(), nullable=False),
        sa.Column("mrc", sa.String(length=100), nullable=False),
        sa.Column("dlmtdr", sa.String(length=5), server_default=",", nullable=False),
        sa.Column("fl_inc_dts", sa.Integer(), server_default="1", nullable=False),
        sa.Column("frmt_fch", sa.String(length=50), nullable=False),
        sa.Column("estd", sa.String(length=20), server_default="Activo", nullable=False),
        sa.ForeignKeyConstraint(
            ["id_sd"],
            ["sd.id_sd"],
        ),
        sa.PrimaryKeyConstraint("id_mp"),
    )
    op.create_table(
        "pnl",
        sa.Column("id_pnl", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_usr", sa.Integer(), nullable=False),
        sa.Column("id_sd", sa.Integer(), nullable=False),
        sa.Column("nmbr", sa.String(length=150), nullable=False),
        sa.Column("vsbldd", sa.String(length=20), server_default="Privado", nullable=False),
        sa.Column(
            "fch_crcn", sa.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["id_sd"],
            ["sd.id_sd"],
        ),
        sa.ForeignKeyConstraint(
            ["id_usr"],
            ["usr.id_usr"],
        ),
        sa.PrimaryKeyConstraint("id_pnl"),
        sa.UniqueConstraint("id_usr", "nmbr", name="uq_pnl_usr_nombre"),
    )
    op.create_index("idx_pnl_sd", "pnl", ["id_sd"], unique=False)
    op.create_table(
        "prms_usr_sd",
        sa.Column("id_prms", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_usr", sa.Integer(), nullable=False),
        sa.Column("id_sd", sa.Integer(), nullable=False),
        sa.Column("mdl", sa.String(length=50), nullable=False),
        sa.Column("nvl", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_sd"],
            ["sd.id_sd"],
        ),
        sa.ForeignKeyConstraint(
            ["id_usr"],
            ["usr.id_usr"],
        ),
        sa.PrimaryKeyConstraint("id_prms"),
        sa.UniqueConstraint("id_usr", "id_sd", "mdl", name="uq_prmsusrsd_usr_sd_mdl"),
    )
    op.create_table(
        "prmtr_clcld",
        sa.Column("id_prm_clc", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_sd", sa.Integer(), nullable=False),
        sa.Column("nmbr", sa.String(length=100), nullable=False),
        sa.Column("frml", sa.String(length=500), nullable=False),
        sa.Column("undd", sa.String(length=30), nullable=False),
        sa.Column("dscrpcn", sa.String(length=300), nullable=True),
        sa.Column("estd", sa.String(length=20), server_default="Activo", nullable=False),
        sa.ForeignKeyConstraint(
            ["id_sd"],
            ["sd.id_sd"],
        ),
        sa.PrimaryKeyConstraint("id_prm_clc"),
        sa.UniqueConstraint("id_sd", "nmbr", name="uq_prmtrclcld_sd_nombre"),
    )
    op.create_table(
        "alrm",
        sa.Column("id_alrm", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_usr", sa.Integer(), nullable=False),
        sa.Column("id_sd", sa.Integer(), nullable=False),
        sa.Column("nmbr", sa.String(length=150), nullable=False),
        sa.Column("id_prmtr", sa.Integer(), nullable=False),
        sa.Column("id_ubccn", sa.Integer(), nullable=False),
        sa.Column("estd", sa.String(length=20), server_default="Activa", nullable=False),
        sa.Column(
            "fch_crcn", sa.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["id_prmtr"],
            ["prmtr.id_prmtr"],
        ),
        sa.ForeignKeyConstraint(
            ["id_sd"],
            ["sd.id_sd"],
        ),
        sa.ForeignKeyConstraint(
            ["id_ubccn"],
            ["ubccn.id_ubccn"],
        ),
        sa.ForeignKeyConstraint(
            ["id_usr"],
            ["usr.id_usr"],
        ),
        sa.PrimaryKeyConstraint("id_alrm"),
    )
    op.create_index("idx_alrm_sd", "alrm", ["id_sd"], unique=False)
    op.create_table(
        "dspstv",
        sa.Column("id_dspstv", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_ubccn", sa.Integer(), nullable=False),
        sa.Column("id_cnxn", sa.Integer(), nullable=False),
        sa.Column("id_mp", sa.Integer(), nullable=False),
        sa.Column("nmbr", sa.String(length=150), nullable=False),
        sa.Column("mrc", sa.String(length=100), nullable=False),
        sa.Column("mdl", sa.String(length=100), nullable=True),
        sa.Column("lttd", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("lngtd", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("estd", sa.String(length=20), server_default="Activo", nullable=False),
        sa.Column(
            "fch_rgstr",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint("lngtd BETWEEN -180 AND 180", name="dspstv_lngtd_check"),
        sa.CheckConstraint("lttd BETWEEN -90 AND 90", name="dspstv_lttd_check"),
        sa.ForeignKeyConstraint(
            ["id_cnxn"],
            ["cnxn_ftp.id_cnxn"],
        ),
        sa.ForeignKeyConstraint(
            ["id_mp"],
            ["mp_frmt.id_mp"],
        ),
        sa.ForeignKeyConstraint(
            ["id_ubccn"],
            ["ubccn.id_ubccn"],
        ),
        sa.PrimaryKeyConstraint("id_dspstv"),
    )
    op.create_index("idx_dspstv_ubccn", "dspstv", ["id_ubccn"], unique=False)
    op.create_table(
        "mp_clmn",
        sa.Column("id_mp_cl", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_mp", sa.Integer(), nullable=False),
        sa.Column("indc_clmn", sa.Integer(), nullable=False),
        sa.Column("id_prmtr", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_mp"],
            ["mp_frmt.id_mp"],
        ),
        sa.ForeignKeyConstraint(
            ["id_prmtr"],
            ["prmtr.id_prmtr"],
        ),
        sa.PrimaryKeyConstraint("id_mp_cl"),
        sa.UniqueConstraint("id_mp", "indc_clmn", name="uq_mpclmn_mp_indccolmn"),
    )
    op.create_table(
        "pnl_ubccn",
        sa.Column("id_pnl_ubc", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_pnl", sa.Integer(), nullable=False),
        sa.Column("id_ubccn", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_pnl"],
            ["pnl.id_pnl"],
        ),
        sa.ForeignKeyConstraint(
            ["id_ubccn"],
            ["ubccn.id_ubccn"],
        ),
        sa.PrimaryKeyConstraint("id_pnl_ubc"),
        sa.UniqueConstraint("id_pnl", "id_ubccn", name="uq_pnlubccn_pnl_ubccn"),
    )
    op.create_table(
        "wdgt",
        sa.Column("id_wdgt", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_pnl", sa.Integer(), nullable=False),
        sa.Column("tp", sa.String(length=30), nullable=False),
        sa.Column("id_prmtr", sa.Integer(), nullable=False),
        sa.Column("id_ubccn", sa.Integer(), nullable=False),
        sa.Column("pscn", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["id_pnl"],
            ["pnl.id_pnl"],
        ),
        sa.ForeignKeyConstraint(
            ["id_prmtr"],
            ["prmtr.id_prmtr"],
        ),
        sa.ForeignKeyConstraint(
            ["id_ubccn"],
            ["ubccn.id_ubccn"],
        ),
        sa.PrimaryKeyConstraint("id_wdgt"),
    )
    op.create_table(
        "cndcn_alrm",
        sa.Column("id_cndcn", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_alrm", sa.Integer(), nullable=False),
        sa.Column("oprdr", sa.String(length=5), nullable=False),
        sa.Column("vlr_umbrl", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.CheckConstraint("oprdr IN ('>','<','>=','<=','=')", name="cndcnalrm_oprdr_check"),
        sa.ForeignKeyConstraint(
            ["id_alrm"],
            ["alrm.id_alrm"],
        ),
        sa.PrimaryKeyConstraint("id_cndcn"),
    )
    op.create_table(
        "dstntr_alrm",
        sa.Column("id_dstntr", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id_alrm", sa.Integer(), nullable=False),
        sa.Column("cnl", sa.String(length=20), server_default="email", nullable=False),
        sa.Column("crr", sa.String(length=150), nullable=True),
        sa.Column("cht_id_tlgrm", sa.String(length=50), nullable=True),
        sa.CheckConstraint(
            "(cnl = 'email' AND crr IS NOT NULL AND cht_id_tlgrm IS NULL) OR (cnl = 'telegram' AND cht_id_tlgrm IS NOT NULL AND crr IS NULL)",
            name="dstntralrm_canal_destino_check",
        ),
        sa.CheckConstraint("cnl IN ('email','telegram')", name="dstntralrm_cnl_check"),
        sa.ForeignKeyConstraint(
            ["id_alrm"],
            ["alrm.id_alrm"],
        ),
        sa.PrimaryKeyConstraint("id_dstntr"),
    )
    op.create_index(
        "uq_dstntr_email",
        "dstntr_alrm",
        ["id_alrm", "crr"],
        unique=True,
        postgresql_where=sa.text("cnl = 'email'"),
    )
    op.create_index(
        "uq_dstntr_telegram",
        "dstntr_alrm",
        ["id_alrm", "cht_id_tlgrm"],
        unique=True,
        postgresql_where=sa.text("cnl = 'telegram'"),
    )
    op.create_table(
        "intnt_prcsmnt",
        sa.Column("id_intnt", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("id_archv", sa.BigInteger(), nullable=False),
        sa.Column(
            "fch_intnt",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("rsltd", sa.String(length=20), nullable=False),
        sa.Column("mnsj_errr", sa.String(length=500), nullable=True),
        sa.Column("id_usr", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_archv"],
            ["archv_ingst.id_archv"],
        ),
        sa.ForeignKeyConstraint(
            ["id_usr"],
            ["usr.id_usr"],
        ),
        sa.PrimaryKeyConstraint("id_intnt"),
    )
    op.create_table(
        "ntfccn_envd",
        sa.Column("id_ntfccn", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("id_alrm", sa.Integer(), nullable=False),
        sa.Column("cnl", sa.String(length=20), nullable=False),
        sa.Column("dstn", sa.String(length=150), nullable=False),
        sa.Column(
            "fch_env", sa.TIMESTAMP(timezone=True), server_default=sa.text("NOW()"), nullable=False
        ),
        sa.Column("estd", sa.String(length=20), nullable=False),
        sa.Column("rntnts", sa.Integer(), server_default="0", nullable=False),
        sa.CheckConstraint("cnl IN ('email','telegram')", name="ntfccnenvd_cnl_check"),
        sa.ForeignKeyConstraint(
            ["id_alrm"],
            ["alrm.id_alrm"],
        ),
        sa.PrimaryKeyConstraint("id_ntfccn"),
    )
    op.create_table(
        "tlmtr",
        sa.Column("id_lctr", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("fch_hr", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id_dspstv", sa.Integer(), nullable=False),
        sa.Column("id_prmtr", sa.Integer(), nullable=False),
        sa.Column("id_sd", sa.Integer(), nullable=False),
        sa.Column("vlr", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("id_archv", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_archv"],
            ["archv_ingst.id_archv"],
        ),
        sa.ForeignKeyConstraint(
            ["id_dspstv"],
            ["dspstv.id_dspstv"],
        ),
        sa.ForeignKeyConstraint(
            ["id_prmtr"],
            ["prmtr.id_prmtr"],
        ),
        sa.ForeignKeyConstraint(
            ["id_sd"],
            ["sd.id_sd"],
        ),
        sa.PrimaryKeyConstraint("id_lctr", "fch_hr"),
        postgresql_partition_by="RANGE (fch_hr)",
    )
    op.create_index(
        "idx_tlmtr_dspstv_prmtr", "tlmtr", ["id_dspstv", "id_prmtr", "fch_hr"], unique=False
    )
    op.create_index(
        "idx_tlmtr_fchhr_brin", "tlmtr", ["fch_hr"], unique=False, postgresql_using="brin"
    )
    op.create_index("idx_tlmtr_sd", "tlmtr", ["id_sd", "fch_hr"], unique=False)
    op.alter_column(
        "archv_ingst",
        "id_archv",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.create_index("idx_archvingst_estd", "archv_ingst", ["estd", "fch_dtccn"], unique=False)
    op.create_index("idx_ubccn_sd", "ubccn", ["id_sd"], unique=False)
    # ### end Alembic commands ###

    # Particiones mensuales iniciales de tlmtr (el job de HT-08/Celery Beat
    # creará las siguientes automáticamente). Alembic no tiene helper para
    # PARTITION OF, se usa SQL crudo.
    op.execute(
        "CREATE TABLE tlmtr_2026_07 PARTITION OF tlmtr "
        "FOR VALUES FROM ('2026-07-01') TO ('2026-08-01')"
    )
    op.execute(
        "CREATE TABLE tlmtr_2026_08 PARTITION OF tlmtr "
        "FOR VALUES FROM ('2026-08-01') TO ('2026-09-01')"
    )
    op.execute(
        "CREATE TABLE tlmtr_2026_09 PARTITION OF tlmtr "
        "FOR VALUES FROM ('2026-09-01') TO ('2026-10-01')"
    )
    op.execute(
        "CREATE TABLE tlmtr_2026_10 PARTITION OF tlmtr "
        "FOR VALUES FROM ('2026-10-01') TO ('2026-11-01')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres borra las particiones automáticamente al hacer drop de la
    # tabla padre, pero se dejan explícitas por claridad/simetría.
    op.execute("DROP TABLE IF EXISTS tlmtr_2026_10")
    op.execute("DROP TABLE IF EXISTS tlmtr_2026_09")
    op.execute("DROP TABLE IF EXISTS tlmtr_2026_08")
    op.execute("DROP TABLE IF EXISTS tlmtr_2026_07")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_ubccn_sd", table_name="ubccn")
    op.drop_index("idx_archvingst_estd", table_name="archv_ingst")
    op.alter_column(
        "archv_ingst",
        "id_archv",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.drop_index("idx_tlmtr_sd", table_name="tlmtr")
    op.drop_index("idx_tlmtr_fchhr_brin", table_name="tlmtr", postgresql_using="brin")
    op.drop_index("idx_tlmtr_dspstv_prmtr", table_name="tlmtr")
    op.drop_table("tlmtr")
    op.drop_table("ntfccn_envd")
    op.drop_table("intnt_prcsmnt")
    op.drop_index(
        "uq_dstntr_telegram", table_name="dstntr_alrm", postgresql_where=sa.text("cnl = 'telegram'")
    )
    op.drop_index(
        "uq_dstntr_email", table_name="dstntr_alrm", postgresql_where=sa.text("cnl = 'email'")
    )
    op.drop_table("dstntr_alrm")
    op.drop_table("cndcn_alrm")
    op.drop_table("wdgt")
    op.drop_table("pnl_ubccn")
    op.drop_table("mp_clmn")
    op.drop_index("idx_dspstv_ubccn", table_name="dspstv")
    op.drop_table("dspstv")
    op.drop_index("idx_alrm_sd", table_name="alrm")
    op.drop_table("alrm")
    op.drop_table("prmtr_clcld")
    op.drop_table("prms_usr_sd")
    op.drop_index("idx_pnl_sd", table_name="pnl")
    op.drop_table("pnl")
    op.drop_table("mp_frmt")
    op.drop_index("idx_lgadtr_usr_fch", table_name="lg_adtr")
    op.drop_index("idx_lgadtr_sd_fch", table_name="lg_adtr")
    op.drop_table("lg_adtr")
    op.drop_table("exprtcn")
    op.drop_table("cbr")
    op.drop_index("idx_sscrpcn_vncmnt", table_name="sscrpcn")
    op.drop_table("sscrpcn")
    op.drop_table("lmt_pln")
    op.drop_table("prmtr")
    op.drop_table("pln_sscrpcn")
    # ### end Alembic commands ###
